play.modules.enabled += "modules.BlackjackModule"

play.http.secret.key = "_7vvbzp?sqSAtFNeahF6x56yPH^F/kBhuvDgrKw::I=Xk]W`B^Rx3Ix3834IHV1]" # Generate with: sbt playGenerateSecret
play.http.session.secure = true # For HTTPS
play.http.session.httpOnly = true

play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.hosts.allowed = ["playserver.herokuapp.com", ".herokuapp.com"]

play.filters.cors {
  allowedOrigins = [
    "http://localhost:8080", 
    "http://localhost:5173",
    "http://127.0.0.1:4000",      // ← Add this (PWA server)
    "http://192.168.0.229:4000"
    ]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Content-Type", "Origin", "X-Requested-With", "Authorization"]
  preflightMaxAge = 1 hour
  allowCredentials = true
}