name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd blackjack-vue
          npm install

      - name: Build
        run: |
          cd blackjack-vue
          npx quasar build -m pwa

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blackjack-vue/dist/pwa

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cd play-server
          git config --global user.email "gallusjonathan@gmail.com"
          git config --global user.name "GitHub Actions"
          heroku git:remote -a playserver-eu
          git push heroku main:main -f